// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0etfZ3A99SlP-1jv7eyd2_pLiU2KXqk',
    appId: '1:463445127865:web:6f42db5259ebf818fb2168',
    messagingSenderId: '463445127865',
    projectId: 'template-flutter-bloc',
    authDomain: 'template-flutter-bloc.firebaseapp.com',
    storageBucket: 'template-flutter-bloc.firebasestorage.app',
    measurementId: 'G-J5P0TKRVDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-xf5QoXJz95PefU1yXxeFGCrsisOhfqo',
    appId: '1:463445127865:android:5c11edd2bc1efea7fb2168',
    messagingSenderId: '463445127865',
    projectId: 'template-flutter-bloc',
    storageBucket: 'template-flutter-bloc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0lHjM9umliDrmvLb6vY-ucdwDVLiynfI',
    appId: '1:463445127865:ios:dffe58a0b770d679fb2168',
    messagingSenderId: '463445127865',
    projectId: 'template-flutter-bloc',
    storageBucket: 'template-flutter-bloc.firebasestorage.app',
    iosBundleId: 'com.example.templateFlutterBloc',
  );
}
